### ISSUE TITLE
[BUG] BIDS validator error 

### ISSUE THREAD

**Issue by Michael-Sun** [bids-apps/afni_proc#18]
### What version of the bids app were you using?

0.0.2

### Describe your problem in detail.

Traceback (most recent call last):
  File "/run.py", line 238, in <module>
    run(('bids-validator %s'%args.bids_dir).split(' '))
  File "/run.py", line 165, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 1

### What command did you run?

Command ran: singularity run -B /dartfs-hpc/rc/lab/C/CANlab/labdata/data/WASABI/1080_wasabi:/bids:ro -B /dartfs-hpc/rc/lab/C/CANlab/labdata/data/WASABI/derivatives/AFNI_PROC:/outputs /dartfs-hpc/rc/lab/C/CANlab/modules/afni_proc.sif /bids /outputs participant --participant_label SID001907

### Describe what you expected.

afni_proc starts.

**Comment by Remi-Gau** [comment]
hum... and of course this app has no way to skip validation... great... 😩

**Comment by Remi-Gau** [comment]
This is the version of the validator that was used:

https://github.com/bids-apps/afni_proc/blob/48c559943097a535064551383e1b001caaf2e0bc/Dockerfile#L76

So you could try to run that bids validator to at least know what's wrong.
